[package]
name = "ai_prompt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
prompts = "0.1.0"
reqwest = "0.12.23"
serde = {version = "1.0.219", features=["derive"]}
tokio = { version = "1.46.0", features = ["full"]}
