[package]
name = "ai_prompt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
prompts = "0.1.0"
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.46.0", features=["full"] }
